version: '3.8'

services:
  bot:
    container_name: crypto-transactor-bot
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: faustis1337/crypto-transactor:latest